name: BareMetal Core
on: [push]
jobs:
  BuildWindows:
    runs-on: windows-2022
    strategy:
      matrix:
        config: [release, debug, checked, final]
        libs: [shared, static]
    env:
      GITHUB_TOKEN: ${{secrets.ONION_GIT_PUBLIC_TOKEN}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
      - uses: lukka/get-cmake@v3.23.0
      - run: |
              git clone https://github.com/BareMetalEngine/onion.git C:\onion
              C:\onion\onion.exe configure
              C:\onion\onion.exe make -config=${{matrix.config}} -libs=${{matrix.libs}}
              C:\onion\onion.exe build
              C:\onion\onion.exe test
  BuildLinux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [release, debug, checked, final]
        libs: [shared, static]
    env:
      GITHUB_TOKEN: ${{secrets.ONION_GIT_PUBLIC_TOKEN}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
      - uses: lukka/get-cmake@v3.23.0
      - run: |
              git clone https://github.com/BareMetalEngine/onion.git ~/onion/
              ~/onion/onion configure
              ~/onion/onion make -config=${{matrix.config}} -libs=${{matrix.libs}}
              ~/onion/onion build
              ~/onion/onion test
