name: BareMetal Core
on: [push]
jobs:
  BuildLinux:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.ONION_GIT_PUBLIC_TOKEN}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
      - uses: lukka/get-cmake@v3.23.0
      - run: |
              git clone https://github.com/BareMetalEngine/onion.git C:\onion
              C:\onion\onion.exe configure
              C:\onion\onion.exe make
              C:\onion\onion.exe build
              C:\onion\onion.exe test
  BuildWindows:
    runs-on: windows-2022
    needs: BuildLinux
    env:
      GITHUB_TOKEN: ${{secrets.ONION_GIT_PUBLIC_TOKEN}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
      - uses: lukka/get-cmake@v3.23.0
      - run: |
              git clone https://github.com/BareMetalEngine/onion.git ~/onion/
              ~/onion/onion configure
              ~/onion/onion make
              ~/onion/onion build
              ~/onion/onion test
